name: learn-github-actions
run-name: ${{ github.actor }} is learning Github Actions
on: [push]
jobs:
  deploy:
    environment: prod
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: install nodejs
        uses: actions/setup-node@v4
        with: 
          node-version: '20'
      - name: move dist to server
        uses: appleboy/scp-action@v0.0.1
        with:
          host: ${{ secrets.REMOTE_USER1 }}
          username: ${{ secrets.REMOTE_USER }}
          password: ${{ secrets.REMOTE_PASS }}
          port: 22
          source: "index.html"
          target: "/MyNginx"
