name: learn-github-actions
run-name: ${{ github.actor }} is learning Github Actions
on: [push]
jobs:
  deploy:
    environment: prod
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: install nodejs
        uses: actions/setup-node@v4
        with: 
          node-version: '20'
      - name: upload file to the server
        uses: zhenyuWang/Upload-File-Action@v1.0.1
        with:
          username: ${{ secrets.REMOTE_USER }}
          server: ${{ secrets.REMOTE_HOST }}
          port: "22"
          ssh_private_key: ${{ secrets.PRIVATE_KEY}}
            # 要上传文件所在目录
          local_path: "./index.html"
            # 远程服务器目标路径
          target_path: "/home/my-nginx/"
